### ISSUE TITLE
可否加入自定义服务器功能

### ISSUE THREAD

**Issue by Zxilly** [project-openwrt/luci-app-unblockneteasemusic-mini#1]
希望可以指定为自建的服务器

**Comment by hank9999** [comment]
你可以尝试修改luci-app-unblockneteasemusic-mini/root/etc/init.d/unblockneteasemusic-mini中的服务器配置

**Comment by 1715173329** [comment]
目前没有这个打算，你可以通过修改init实现指向你自己的服务器。
