### ISSUE TITLE
打开以后手机app刷不出歌单

### ISSUE THREAD

**Issue by kidd31** [project-openwrt/luci-app-unblockneteasemusic-mini#3]
iphoneXR 13.3.1
已经安装并信任根证书

**Comment by madman43** [comment]
同样iphone8 ios13.3.1
已经安装并信任根证书
歌单刷不出来，提示失联

**Comment by 1715173329** [comment]
iPhoneSE iOS13.3.1
网易云音乐7.0.10

目前正常工作。。。

**Comment by madman43** [comment]
> iPhoneSE iOS13.3.1
> 网易云音乐7.0.10
> 
> 目前正常工作。。。

我关闭服务重启开启好像就正常了……

**Comment by madman43** [comment]
不过还是有点小问题，时不时失联，无法获取歌单和获取了歌单，里面的有些歌提示网络不好 无法播放
