### ISSUE TITLE
OpenWrt作为旁路由时开启无效

### ISSUE THREAD

**Issue by MarkSong2020** [project-openwrt/luci-app-unblockneteasemusic-mini#5]
您好，我目前是esxi上挂双软路由，主路由ROS，旁路由OpenWrt，在OpenWrt开启插件后，解锁未成功。

**Comment by 1715173329** [comment]
@MarkSong2020 怎么个无效法。。

**Comment by 1715173329** [comment]
@MarkSong2020 证书看了么？网关设定好了么？防火墙规则确认生效了么？确认无其他插件冲突么？网络确定没问题么？

**Comment by MarkSong2020** [comment]
> @MarkSong2020 怎么个无效法。。

PC端登录网易云web网站 music.163.com 返回超时 ERR_CONNECTION_TIMED_OUT
windows客户端打开后主页能访问，点击每日推荐或歌单后无响应。

相同PC环境，换了k2p运行插件是正常的，所以初步怀疑是双软路由导致的问题。

**Comment by 1715173329** [comment]
@MarkSong2020 先检查下，你的旁路，是不是到解锁服务器的链路有问题

另外，如果使用clash (fake-ip) 这类，亦会导致无法正常使用

**Comment by MarkSong2020** [comment]
![image](https://user-images.githubusercontent.com/61323122/75181955-557b6c00-577a-11ea-9b4b-9877baddbda8.png)
旁路到解锁服务器的链路应该是通的，我ssh到旁路ping是通的
clash (fake-ip) 这类具体要怎么查看？不好意思，编程小白。

**Comment by 1715173329** [comment]
@MarkSong2020 如果你没使用clash的话，就不用考虑了。。

另外，可以路由器上执行下 wget -O- https://music.163.com 看看是什么情况

**Comment by MarkSong2020** [comment]
![image](https://user-images.githubusercontent.com/61323122/75183540-b5bfdd00-577d-11ea-979d-8a5f65acb67f.png)
返回一个html页面

**Comment by 1715173329** [comment]
@MarkSong2020 看起来旁路本身没啥问题。。
那就可能是你网关设置问题了。。。

本人没有旁路这种环境，恕无法提供有效解决方案，可以看看其他人有没有相关指导意见。。

**Comment by js882829** [comment]
我也是旁路由，遇到的问题一模一样。用别的解锁就行。用MINI就报网络超时。麻烦大神有空解决一下。

**Comment by fefz** [comment]
我也遇到了，100%复现。

**Comment by 1715173329** [comment]
@js882829 我寻思着防火墙规则都是一样的。。
旁路请自行解决网关问题。
另外，你都有钱上旁路了，自行运行本地解锁程序，请。本插件仅为小flash路由器设计。

**Comment by js882829** [comment]
> @js882829 我寻思着防火墙规则都是一样的。。
> 旁路请自行解决网关问题。
> 另外，你都有钱上旁路了，自行运行本地解锁程序，请。本插件仅为小flash路由器设计。

好的，感谢回复！

**Comment by StoneForests** [comment]
> > @MarkSong2020 怎么个无效法。。
> 
> PC端登录网易云web网站 music.163.com 返回超时 ERR_CONNECTION_TIMED_OUT
> windows客户端打开后主页能访问，点击每日推荐或歌单后无响应。
> 
> 相同PC环境，换了k2p运行插件是正常的，所以初步怀疑是双软路由导致的问题。

我跟你的情况基本一样，爱快主路由，op旁路由，op中运行mini版的插件就会浏览器打不开music.163.com主页，pc客户端只打得开主页但是其它任何地方点了都没有反应
