### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by klever1988** [project-openwrt/luci-app-unblockneteasemusic-mini#6]
![image](https://user-images.githubusercontent.com/56048681/75484254-5e22ab00-59e3-11ea-9716-46f6eadd7a72.png)

域名music.163.com的证书是letsencrypt签发的cdn域证书，并不是unblockneteasemusic ca签发的

**Comment by 1715173329** [comment]
@klever1988 低音质服务器？

**Comment by 1715173329** [comment]
该问题已处理。
