### ISSUE TITLE
与openwrt主题不兼容

### ISSUE THREAD

**Issue by yiguihai** [project-openwrt/luci-app-unblockneteasemusic-mini#9]
https://github.com/project-openwrt/luci-app-unblockneteasemusic-mini/blob/a4651bdd7f012ab045d8e598b2bfd839be7228f9/luasrc/model/cbi/unblockneteasemusic-mini.lua#L5
![2020-06-07 19-38-49屏幕截图](https://user-images.githubusercontent.com/22967964/83967746-d0fec480-a8f6-11ea-98f5-dae271397ed6.png)
使用luci-theme-openwrt主题时报错，删除html的代码可以正常运行

**Comment by ElonH** [comment]
```
-OpenWrt & hyird & Sunsky 
```
中`&` 要转码成 `&amp;`

**Comment by AmadeusGhost** [comment]
What version of luci do you use?

**Comment by yiguihai** [comment]
> What version of luci do you use?

19.07.3

**Comment by yiguihai** [comment]
问题已解决，忘记说感谢了

感谢大家
